### ISSUE TITLE
General UI roughness

### ISSUE THREAD

**Issue by sliptonic** [CADCloud/CADCloud#1]
This project being early, the UI doesn't need to be smooth or beautiful yet.  The following are a couple things that confused me enough that they should probably be addressed.

1) There's no way to dismiss the 3D window once a model is clicked.  It should be possible to return to the previous state of the webpage from any action.

2) Refreshing the page loses the login status. 

3) Going to the home page presents the 'create account' dialog even if the user is logged in.

4) Pointer behavior is strange.  Most of the links that work show a mouse 'text insert' pointer instead of the standard finger pointer.  The placeholder links show the finger but don't work since they're just placeholders.  

5) In the 3D window, the assembly list includes '+' icons for lines that are collapsed but clicking the icon does nothing.  Clicking the text expands/collapses as expected or toggles visibility.  It should probably be only visibility and expand/collapse should only be on the icon.

6) The python keynames on the account page don't match the keynames required in the python code.  
Web page                                  Python Code
=========                                ============
TokenAuth                                 cloudaccesskey
TokenSecret                              cloudsecretkey

7) Web page has a 'project page' but it's not clear how to create a project.  A little text help here will go a long way.

**Comment by vejmarie** [comment]
Hi,

I agree the look and feel is not that easy. I mostly focus on trying to make work the basic. But to help

1- if you click outside the model window, the 3D shall disappear. I thought it would have been intuitive enough (or try to press escape key), so it is not ! I will put back a cross to the top right.

2- It is an intentional behavior, which seems crazy. I am trying to make work the service without any cookies at all. So everything is stored in memory, so when you refresh the page you loose everything including your login info !. My argument is perhaps stupid, but with RGPD, privacy etc etc, I thought the best way to handle it was to remove cookie usage. Perhaps too disturbing

3- Good remark.

4- We need to enhance that

5- Yes I have seen that. In fact I build the tree in a quick and dirty manner for some people at the OCP foundation who wanted to see if we could make it.

6- Yes I agree. My brain is messy in some cases, and if you look at the source code you will see this issues in many places. I really need to clean that stuff.

7- This is ongoing work.

Can you open an issue for each of this important remarks as we could track them ?

**Comment by sliptonic** [comment]
Closing issue.  Individual items have been recreated as separate issues.
