### ISSUE TITLE
Each uploaded part/project needs an url.

### ISSUE THREAD

**Issue by sliptonic** [CADCloud/CADCloud#34]
Each project should have a shareable url that leads directly to the project details.
 
If the project is publicly downloadable, the url should lead to a screen where there's an ID that can be used to retrieve the model.

**Comment by vejmarie** [comment]
I think I might have a first implementation in about 5-7 days. I started to think about it tonight and the URL might be looking at something like this:
https://<your server>/getProject/2020-04-19/vejmarie/test
https://<your server>/getViewer/2020-04-19/vejmarie/test
I need to get the revision count into it. Projects are sorted by date, or latest updated date, but it will be available directly from the project page as a shareable link so that shall be ok.

I'll be providing I think 2 URL, one for the Project which will return a full web page, and one for the embedded 3D viewer, which could be integrated into web pages. The challenge with the viewer will be to make it fit into something. I Currently use an iFrame, but it could be tricky in many cases. Any idea ? I can provide the code to be embedded into a div.

**Comment by vejmarie** [comment]
I just opened PR#41 which is introducing such feature. Can you check if that works ?
To do so, create a new project, go to the project page as being connected, you will be seeing links at the bottom appearing. The first one (and only the first one) shall be working if you go into a new browser, if your project is public. The page layout is super basic, but we can enhance that later. I need to discuss with you about the embedding of the 3D player. I think it is doable, but I need to check a few things first.
