### ISSUE TITLE
Normalize token names and python keynames

### ISSUE THREAD

**Issue by sliptonic** [CADCloud/CADCloud#8]
The 'my account' page contains tokens for configuring the python upload function.  The names of these tokens don't correspond to the keynames used in python.  

Recommend these be normalized to avoid user confusion.  

Web page Python Code
========= ============
TokenAuth cloudaccesskey
TokenSecret cloudsecretkey

**Comment by vejmarie** [comment]
What do you think about changing the name in FreeCAD ? I don't like them because they are pretty long and redundant in the end we have Cloud.cloudaccesskey ... Cloud.TokenAuth seems more relevant to me in the end. I can align in your proposed way, but I think we shall be more focused on the naming into the FreeCAD Cloud module. Or something like Cloud.AccessKey might be more relevant, which means changing in both, but I am ok with that either.

**Comment by sliptonic** [comment]
That sounds good to me .  As long as what's shown on screen and what's in the python are unambiguously the same thing, it's fine.

**Comment by vejmarie** [comment]
I made a PR into FreeCAD to re-align against CADCloud. I also simplified the command

https://github.com/FreeCAD/FreeCAD/pull/3329

Which are becoming

Cloud.URL
Cloud.TCPPort
Cloud.TokenAuth
Cloud.TokenSecret
Cloud.Save
Cloud.Restore

Hopefully it will go through

**Comment by vejmarie** [comment]
This has been merged into FreeCAD we can close it !
